steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.6
      - 1.6/jessie
    id: '1.6'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.6-slim
      - 1.6/slim
    id: '1.6-slim'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.8
      - 1.8/jessie
    id: '1.8'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.8-slim
      - 1.8/slim
    id: '1.8-slim'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.9
      - 1.9/jessie
    id: '1.9'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine-go:1.9-slim
      - 1.9/slim
    id: '1.9-slim'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/appengine-go:1.9', 'gcr.io/$PROJECT_ID/appengine-go:latest']
    wait_for: ['1.9']
    id: 'latest'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/appengine-go:1.9-slim', 'gcr.io/$PROJECT_ID/appengine-go:slim']
    wait_for: ['1.9-slim']
    id: 'slim'

images:
  - gcr.io/$PROJECT_ID/appengine-go:latest
  - gcr.io/$PROJECT_ID/appengine-go:slim
  - gcr.io/$PROJECT_ID/appengine-go:1.6
  - gcr.io/$PROJECT_ID/appengine-go:1.6-slim
  - gcr.io/$PROJECT_ID/appengine-go:1.8
  - gcr.io/$PROJECT_ID/appengine-go:1.8-slim
  - gcr.io/$PROJECT_ID/appengine-go:1.9
  - gcr.io/$PROJECT_ID/appengine-go:1.9-slim

timeout: '20m'
