steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine/go:1.11-alpine
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - tag
      - gcr.io/$PROJECT_ID/appengine/go:1.11-alpine
      - gcr.io/$PROJECT_ID/appengine/go:alpine

images:
  - gcr.io/$PROJECT_ID/appengine/go:1.11-alpine
  - gcr.io/$PROJECT_ID/appengine/go:alpine

timeout: 600s
