steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/appengine/go:1.9-jessie
      - .
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - tag
      - gcr.io/$PROJECT_ID/appengine/go:1.9-jessie
      - gcr.io/$PROJECT_ID/appengine/go:1.9

images:
  - gcr.io/$PROJECT_ID/appengine/go:1.9-jessie
  - gcr.io/$PROJECT_ID/appengine/go:1.9

timeout: 600s
